microsoft/PowerApps-TestEngine

- docs/Browser.md
- src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs
Unhelpful exception thrown when incorrect browser is specified.
Doc updated as below
> Handling browser not found exception

- docs/CommandInput.md
- src/Microsoft.PowerApps.TestEngine.Tests/Config/TestStateTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppsUrlMapperTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/TestEngineTests.cs
- src/Microsoft.PowerApps.TestEngine/Config/ITestState.cs
- src/Microsoft.PowerApps.TestEngine/Config/TestState.cs
- src/Microsoft.PowerApps.TestEngine/ISingleTestRunner.cs
- src/Microsoft.PowerApps.TestEngine/PowerApps/IUrlMapper.cs
- src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppsUrlMapper.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
- src/Microsoft.PowerApps.TestEngine/TestEngine.cs
- src/PowerAppsTestEngine/InputOptions.cs
- src/PowerAppsTestEngine/Program.cs
- src/PowerAppsTestEngine/config.json
Allow users to be able to specify what domain they want to target. Default will be: "apps.powerapps.com".
> Allow users to specify domain

- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
- src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs
Test engine hard coded the step to click on the "stay signed in?" page during the sign-in process. For users with specific settings, they may not have the page, which blocks the test execution. Do not wait for 'Stay Signed In' if not present
> Skip 'Stay Signed In' if not present

- src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
- src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs
- src/nuget.config
- The bug is that the SetProperty function only works for Table inputs like` Table( { Value: "Strawberry" }, { Value: "Vanilla" } )`. It should work for inputs like `Table({Color:"red"}, {Color:"green"}, {Color:"blue"})` as well. The previous code hard coded the property to be retrieved to be "Value". 
- Updated PowerFX version as we are out-of-date.
> Fix SetProperty with Table input

- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppFunctionsTest.cs
- src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
- src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs
- src/Microsoft.PowerApps.TestEngine/TestInfra/ITestInfraFunctions.cs
- src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs
- src/nuget.config
Modify SetProperty to work with JSSDK
- Fix the issue that _RunJavascriptAsync<T>(string jsExpression, string[] arguments)_ causes BadParameter error in PA-Client. Replace with _RunJavascriptAsync<T>(string jsExpression)_
- Merge in a main branch bug fix into JSSDK feature branch (when reviewing, I suggest review each commit respectively to avoid confusion)
> Modify SetProperty to work with JSSDK

- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppFunctionsTest.cs
- src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs
Handling legacy webplayer support.
- This can be done by checking if the PowerAppsTestEngine global object is loaded when testengine runs. Ideally, this should exist in serverside on load, if OnePlayer in use. 
- So, if not present we can proceed by injecting embedded JS.
> Handling legacy player support

- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppFunctionsTest.cs
- src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs
Fixing timeout by handling legacy webplayer check in a separate method and not with the appidle check.
> Handling legacy player code extracted to separate method and avoiding timeout

- src/Microsoft.PowerApps.TestEngine.Tests/Helpers/ExceptionHandlingHelperTest.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppFunctionsTest.cs
- src/Microsoft.PowerApps.TestEngine/Helpers/ExceptionHandlingHelper.cs
- src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
Handling published app without JSSDK errorcode. 
- Serverside JSSDK (specifically the webplayer-testengine package) throws an errorcode 1 if published app maybe be outdated.
- This work involves capturing that errorcode and handle it by logging it as an error with a message to republish the app.
- Please note that each testengine functions were handled here.
- The exceptions of each functions (getAppStatus, buildObjectmodel, etc..)are handled in `src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs `.
> Handling published without JSSDK errorcode

- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppFunctionsTest.cs
- src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine/JS/CanvasAppSdk.js
- src/Microsoft.PowerApps.TestEngine/JS/PublishedAppTesting.js
- src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs
- src/Microsoft.PowerApps.TestEngine/TestInfra/ITestInfraFunctions.cs
- src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs
We used to use URI encoding to prevent JS script injection. This change is to using JSON encoding instead due to the fact that it's about JS code.
> Use JSON encoding instead of URI encoding for SetProperty

- src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
- src/PowerAppsTestEngine/PowerAppsTestEngine.csproj
- Use Playwright 1.22.0 in all the places
- Remove unnecessary package reference
Note: The GitHub Action integration tests have been using Playwright 1.22.0 for a while so it should be safe to upgrade.
> Use Playwright 1.22.0

- .github/workflows/yaml-integration-tests.yml
- src/Microsoft.PowerApps.TestEngine.Tests/Reporting/TestReporterTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine/Reporting/ITestReporter.cs
- src/Microsoft.PowerApps.TestEngine/Reporting/TestReporter.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
- TestEngine Yaml-Integration tests fails frequently with the error (**Error: td.UnitTest is not iterable**)
```
Creating test report Sample Tests
Processing test results from TestResults/0ba[44](https://github.com/microsoft/PowerApps-TestEngine/actions/runs/4058670848/jobs/6999496015#step:4:46)3/Results_0ba44369-b153-49c5-bae5-dbf5c69d7fe4.trx
Processing test results from TestResults/0ce064/Results_0ce06468-6ad0-41b5-ab2d-03c43d071b46.trx
Processing test results from TestResults/2bb9ce/Results_2bb9cea4-86b7-4832-88f0-87ef4057fdb6.trx
Processing test results from TestResults/3471b1/Results_3471b1e2-0422-4d95-ba87-ee8786fed56d.trx
Processing test results from TestResults/3afabc/Results_3afabc51-7aec-48db-8ae9-b6577683baa5.trx
Processing test results from …
```
> Fix Integration test

- src/Microsoft.PowerApps.TestEngine.Tests/Reporting/TestReporterTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine/Reporting/ITestReporter.cs
- src/Microsoft.PowerApps.TestEngine/Reporting/TestReporter.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
Previous fix handled not executed tests as skipped but handle it as failed.
https://github.com/microsoft/PowerApps-TestEngine/pull/203
> Handle skipped tests as failed tests

- docs/Yaml/testSettings.md
- src/Microsoft.PowerApps.TestEngine.Tests/TestEngineTests.cs
- src/Microsoft.PowerApps.TestEngine/TestEngine.cs
This is a very small log message change. For the log message that informs the user when the locale field is missing in the test plan file, the log type has been changed from INFO to WARN to better indicate the nature of the message. I have added one more unit test to specifically look for this, as this is a "required" user facing change.
This now looks like this - 
Also a small branding related correction has been made to the `testSettings.md` readme - changed phrase `PowerFx` to `Power Fx` to comply with the correct terminology.
> Changed unspecified locale log message from INFO to WARN

- src/PowerAppsTestEngine/PowerAppsTestEngine.csproj
Currently console app targets two versions and for every dotnet run you would need to pass -f with version explicitly.
` dotnet run -f net6.0 `
Console app targets to net6.0. but the project dll can run on multiple versions. After this change
you can run testengine using just `dotnet run`
> Targetting console app to net6.0

- src/Directory.Build.props
When run locally, unittests are non-discoverable.
The output directory for each project needs to have the target attribute.cs file generated. 
Setting ` GenerateTargetFrameworkAttribute` to false in the Directory.Build.props would result in this C# source file not generated. Previously, the below marked file was not generated. 
This would have adverse effect when targeting the right version. 
- Earlier xUnit.net was targetting .NET 4.0 
- And with the change it targets or points to the correct version .NET 6.0.
Thus, the tests are discovered correctly solving this issue.
> Unit tests non-discoverable running locally.

- clean.cmd
Ignore samples folder when running clean.cmd
> Ignore samples folder when running clean.cmd

- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/Functions/AssertFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/Functions/AssertFunction.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
The intended assertion message should print instead of a long exception, in the case that it's the assert function that fails.
> Print assertion message in the case of assertion failure

- src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs
The current logic for getting the relative path for the embedded JSSDK (`JS\CanvasAppSdk.js` and `JS\PublishedAppTesting.js`) returns the current working directory path and therefore does not account for the application running from any directory (i.e., executable path added to the PATH variable and invoked from anywhere on the computer). Due to this, when executed from outside the source code default build output, the application looks for the embedded JSSDK within the directory from where the command was invoked (e.g., `C:\Users\{username}\Desktop\JS\CanvasAppSdk.js`) which is clearly incorrect.
This logic has now been changed wherein we will now compute the path to the executing assembly so that irrespective of where the application is invoked from, the relative path to the embedded …
> Fixed Relative Path for Embedded JSSDK

- src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
This is a minor change made to dependent packages for compatibility reasons - 
- Some packages were in preview versions and these have been corrected to use versions that align with consuming applications (e.g. PAC CLI) for compatibility (e.g. DependencyInjection has to be 6.0 to be compatible with net5.0 of PAC CLI)
- Few others were also changed just so that they align with the versions used in PAC CLI as well
- Full set of tests were run and no test failures were observed - i.e. no code changes or changes in functionality.
> updated preview version packages to use stable release versions

- src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
- src/nuget.config
Due to a breaking pipeline for PAC CLI caused due to an issue with localization configuration in the downstream dependency `PowerFx.Interpreter` we needed to update the `PowerFx.Interpreter` version to a version more recent than what we have currently. This issue has been fixed in [this PR](https://github.com/microsoft/Power-Fx/pull/839) on the Power Fx repository, and we need to consume this change to unblock our pipeline. To solve this the nuget feed has been updated to consume more recent releases from an alternate pipeline, and subsequently the `PowerFx.Interpreter` version has been updated to a more recent version available in this feed, that fixes the issue.
> Changed NuGet Feed URL for PowerFx Packages and Updated PowerFx.Interpreter version

- src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
- src/nuget.config
Reverts microsoft/PowerApps-TestEngine#246 - 
- This change was originally intended for pulling this dependency from an alternate source to mitigate an underlying bug - this is no longer required.
- We have an alternate mitigation in the consuming application to work around this bug so this PR is being reverted.
> Revert "Changed NuGet Feed URL for PowerFx Packages and Updated PowerFx.Interpreter version"

- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/Functions/AssertFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/Functions/AssertFunction.cs
- src/Microsoft.PowerApps.TestEngine/System/AssertionFailureException.cs
Right now, this exception is being handled on the PAC CLI by being a generic exception with "Assertion failed" appended to it. However, we want the PAC CLI to be able to identify it by the exception, not by the string. In addition, after localization, this may fail. This is also coupling the two code-bases together.
> Add AssertionFailureException

- src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
- src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs
Upgrade to Playwright 1.33 from 1.22. Refactor of HandleUserPasswordScreen to use WaitForURLAsync and remove obsolete code that uses Page.RunAndWaitForNavigationAsync
> Update to 1.33 and remove obsolete RunAndWaitForNavigationAsync

- src/Microsoft.PowerApps.TestEngine.Tests/ConsoleOutputTests.cs
A unit test issue was introduced to a pipeline in a previous commit. Linux and Windows use different characters for newlines. The unit tests pass (linux) but the pipeline fails (windows)
> Fix unit tests

- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
- src/Microsoft.PowerApps.TestEngine/TestInfra/ITestInfraFunctions.cs
- src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs
Disposing playwright assets .Additionally check for disposing the browser instance as well if not already done in any case.
> Dispose PW instance after running the TestEngine

- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/PowerFxEngineTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/PowerFxHelperTests.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/PowerFxEngine.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/PowerFxHelper.cs
Splitting by semicolon is not the right way to extract out the test steps from the whole expression as it could be present anywhere in comments, string literals, or interpolated strings. This pr utilizes PowerFx lexer to attempt to correctly compute the test steps in the formula. The logic is locale specific.
> Fixing how test steps are extracted in case we need to go step by step

- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/PowerFxHelperTests.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/PowerFxEngine.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/PowerFxHelper.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/Span.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/Visitors/DetermineNearestFormulaSeparationForSpansVisitor.cs
Rewriting the logic to extract formulas separated by semicolon (chaining operator). Takes the nested formula separation into account. When parse tree has syntax errors (not the binding errors, which are resolved by going step by step), a best effort is made to extract the test steps as accurately as possible. Firstly, an expression is tokenized if there's a need to go step by step and the spans for formulas between tokens that represent semicolons or chaining operators are computed. These spans are the formulas separated by semicolon. Some of these spans represent formulas that are separated somewhere down the tree (depth > 1, nested separation). Parse tree is used to merge these nested spans into spans that represent formulas separated at the top most level. This logic relies on a …
> Rewriting logic to compute formulas separated by chaining operator and consider nested formula separation.

- src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs
Due to frequent instances of timeouts during test execution, we've decided to remove the `WaitUntil = WaitUntilState.NetworkIdle` property from the `GotoAsync` invocation. From the [Playwright documentation](https://playwright.dev/docs/api/class-page#page-wait-for-url-option-wait-until), it has been suggested NOT to use the `NetworkIdle` property due to its nature of timing out explicitly at 500ms which is undesirable in a real-world scenario (since we can never expect real world network reliability within such tight tolerances).
By removing the explicit setting, the `WaitUntil` property defaults to the [JavaScript `Window.Load`](https://developer.mozilla.org/en-US/docs/Web/API/Window/load_event) event. This makes this function call more robust as it waits until the entire page loads and …
> Avoid GoToUrlAsync from Timing Out Due To Network Idle

- src/Microsoft.PowerApps.TestEngine.Tests/ConsoleOutputTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine/ITestEngineEvents.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
- src/Microsoft.PowerApps.TestEngine/TestEngineEventHandler.cs
Console TestSuite summary is wrong when run with multiple browser config .
**After fix:**
> Fix multiplebrowser suitesummary

- src/Microsoft.PowerApps.TestEngine.Tests/Reporting/TestReporterTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine/Reporting/Format/TestErrorInfo.cs
- src/Microsoft.PowerApps.TestEngine/Reporting/Format/TestOutput.cs
- src/Microsoft.PowerApps.TestEngine/Reporting/ITestReporter.cs
- src/Microsoft.PowerApps.TestEngine/Reporting/TestReporter.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
As an effort to improve the TRX. file >> removing errorinfo stacktrace from .trx
> Remove ErrorInfo stacktrace from trx

- src/Microsoft.PowerApps.TestEngine.Tests/Reporting/TestReporterTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine/Reporting/ITestReporter.cs
- src/Microsoft.PowerApps.TestEngine/Reporting/TestReporter.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
Currently **app URL** and **test results** path is not specified in the .trx file.
In an attempt to improve .trx file >> adding these details.
**Proposed Solution**
- Add app url and test results path as part of ResultSummary within a test run. Keeping in mind the schema http://microsoft.com/schemas/VisualStudio/TeamTest/2010 
- XML change would look like this 
- TRX opened in Visual studio looks like this
Also removed Testcase name within the unittest results.
Since the testcase name is already present in the UnitTestResult attribute
> Adding test results path and app url to TRX

- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppFunctionsTest.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerFXModel/ControlRecordValueTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/Functions/SetPropertyFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/Functions/SomeOtherUntypedObject.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/PowerFxHelperTests.cs
- src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/Functions/WaitFunction.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/PowerFxEngine.cs
With the upgrade to PowerFx.Interpreter from 0.2.3-preview to 0.2.6-preview, some implementation details have changed - 
1. `DateValue.Value` is now deprecated in favor of `DateValue.GetConvertedValue(timeZone)`, and if `timeZone` is `null`, it will use the local timezone. This change has been made to factor this in without change in functionality.
2. The `locale` parameter has been temporarily removed from `PowerFxConfig` constructor to unblock us from fixing other compile time errors, and work on this fix and test it in isolation.
3. The implementation of `IUntypedObject` interface has been updated per the updated interface.
Most of the checklist items are not applicable as these are in-progress changes being done on an intermediate branch to facilitate parallel efforts on the many …
> Refactor DateValue field and fix other compile time errors

- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/PowerFxEngineTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/PowerFxHelperTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/IPowerFxEngine.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/PowerFxEngine.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/PowerFxHelper.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
**With Power Fx Interpreter version 0.2.6-preview**
PowerFxConfig constructor to no longer accept Locale as an input parameter.  This immediately breaks Test Engine's support for localization in Test Plans. The PowerFx PR with the changes >> https://github.com/microsoft/Power-Fx/pull/1292/files#diff-9022339f3f8c7c746994da6ac3f95ec05eadaaae5a3eb5ddd7691a226af4a279. 
**Problem to Solve**
Support localization in Test Engine.
**Proposal**
Supporting 2 current scenarios
1.  Running teststeps with no syntax errors (Run engine.eval once for multiple test steps)
- Pass **locale** as a ParseOption within Microsoft.PowerFx.RecalcEngine.Eval() when executing test steps
2. Running teststeps with syntax errors (Run engine.eval step by step)
- Pass **locale** when spliting test steps >> …
> Support localization with updated PowerFx version

- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppFunctionsTest.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/PowerFxEngineTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine/PowerApps/IPowerAppFunctions.cs
- src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/IPowerFxEngine.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/PowerFxEngine.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
1. When the canvas published app is initialized >> there could be a delay in registration of published app JSSDK.
2. If the TestEngine functions including getAppStatus is executed it returns COMMAND NOT FOUND error >> which in turn is interpreted as published app Test Engine JSSDK not found >> though it is still in process.
**PROPOSAL**
- Call TestEngine ready function from TE before any other functions are executed. This way the rest of the functions >> registered (in the app side) before executing them.
- With this implementation, lifecycle of TE function execution would look like 
_Run TE >> execute **ready function** successfully >> execute other function like getAppStatus.._
We just need to make sure TE continue supporting old apps (back compatibility >> older apps won't have this …
> Implementing ready function

- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/PowerFxEngineTests.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/PowerFxEngine.cs
With the PowerFx version upgrade to 0.2.6-preview >> Run differentVariableTypes sample Or have a Rating control in powerapps and run test like `Setproperty(Rating.Value, 5)`. Below error thrown
By default in the ParserOptions of PowerFxEngine, NumberIsFloat is set to false. i.e, it is considered as decimal.
Currently PowerApps does not support decimal fully but floating-point numbers. Hence, we need to set this NumberIsFloat config to true in TestEngine.
Set parserconfig **Numberisfloat** config to true
> Handling setProperty invalid argument type error when value is number

- src/Microsoft.PowerApps.TestEngine.Tests/Reporting/TestReporterTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine/Reporting/ITestReporter.cs
- src/Microsoft.PowerApps.TestEngine/Reporting/TestReporter.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
Test reporter Test run storage name is useful to differentiate each trx report if parsed or consumed by trx parsers.
Currently it is set to hardcoded default value of **Todo** for every trx report generated. 
We need to change this from "Todo" to something meaningful and that can differentiate **each test run**.
- Use the same **trx** file names used >> **Results_{TestRunId}** instead of Todo.
- This way it is easily identifiable and meaningful
> Setting test reporter testrun storage

- samples/calculator/testPlanWithCommaForDecimal.fx.yaml
- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppFunctionsTest.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerFXModel/ControlRecordValueTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/Functions/SetPropertyFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/Functions/SomeOtherUntypedObject.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/PowerFxEngineTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/PowerFxHelperTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
- src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/Functions/WaitFunction.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/IPowerFxEngine.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/PowerFxEngine.cs
- src/Microsoft.PowerApps.TestEngine/PowerFx/PowerFxHelper.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
This PR upgrades the version of Microsoft.PowerFx.Interpreter to 0.2.6-preview, and addresses any compile time and breaking changes and also updates tests associated with this upgrade.
> Upgrade PowerFx.Interpreter library to 0.2.6-preview

- src/Microsoft.PowerApps.TestEngine.Tests/ConsoleOutputTests.cs
- src/Microsoft.PowerApps.TestEngine/TestEngineEventHandler.cs
Currently source=testengine is not shown part of the app url in console output.
But this **console output is incorrect**, we need this to **dynamically load published&webplayer app JSSDK**.
**Solution**
Not replacing source=testengine from appurl  in console output
> Fixing console url

- docs/PowerFX/README.md
Updated the Power Fx section of our doc to remove statement indicating "any Power Fx function supported". Also added a link to SetProperty page.
- [N/A] The code change is covered by unit tests. I have added tests that prove my fix is effective or that my feature works
- [N/A] I have performed end-to-end test locally.
- [N/A] New and existing unit tests pass locally with my changes
- [N/A] I have commented my code, particularly in hard-to-understand areas
> Updated docs\PowerFx and added link to SetProperty page

- src/Microsoft.PowerApps.TestEngine.Tests/Helpers/PollingHelpersTest.cs
- src/Microsoft.PowerApps.TestEngine/Helpers/PollingHelper.cs
A Moq 'strict' failure was printing when an issue was logged, instead of what was actually supposed to be logged. This is because the logger must be setup in every test in this file, which it was not. Verified locally, this is what it looks like now:
> Fix Issue Where Moq Prints instead of actual Error

- src/Microsoft.PowerApps.TestEngine.Tests/TestEngineTests.cs
- src/Microsoft.PowerApps.TestEngine/TestEngine.cs
Removed `Guid.Empty` from input sanitization with the idea as we don't want to error out the application for a valid Guid that has a value of "empty".
> CLI Input Sanitization

- .github/workflows/build-test.yml
- azure-pipelines.yml
This PR adds CodeQL tasks to the build pipelines in this repo.
- [N/A] The code change is covered by unit tests. I have added tests that prove my fix is effective or that my feature works
- [N/A] New and existing unit tests pass locally with my changes
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
- [N/A] My changes generate no new warnings
> Added CodeQL Tasks to Build Pipelines

- src/Microsoft.PowerApps.TestEngine.Tests/Config/TestStateTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/Config/YamlTestConfigParserTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/ConsoleOutputTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/Helpers/LoggingHelpersTest.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppFunctionsTest.cs
- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/TestEngineTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/Users/UserManagerTests.cs
- src/Microsoft.PowerApps.TestEngine/Config/ITestConfigParser.cs
- src/Microsoft.PowerApps.TestEngine/Config/ITestState.cs
- src/Microsoft.PowerApps.TestEngine/Config/TestState.cs
- src/Microsoft.PowerApps.TestEngine/Config/YamlTestConfigParser.cs
- src/Microsoft.PowerApps.TestEngine/Helpers/LoggingHelper.cs
- src/Microsoft.PowerApps.TestEngine/JS/CanvasAppSdk.js
- src/Microsoft.PowerApps.TestEngine/Reporting/TestLogger.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
- src/Microsoft.PowerApps.TestEngine/System/FileSystem.cs
- src/Microsoft.PowerApps.TestEngine/System/IFileSystem.cs
- src/Microsoft.PowerApps.TestEngine/System/UserAppException.cs
- src/Microsoft.PowerApps.TestEngine/System/UserInputException.cs
- src/Microsoft.PowerApps.TestEngine/TestEngine.cs
- src/Microsoft.PowerApps.TestEngine/TestEngineEventHandler.cs
- src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs
- src/Microsoft.PowerApps.TestEngine/Users/UserManager.cs
**User input errors** are not handled gracefully. This is keeping in mind the behavior with the consumption of test engine in PAC CLI. Few cases below handled. 
Also updated a case to handle as **User app exception**. This will help us isolate this type and localize in PAC CLI side.
Categorizing mainly these specific errors into
1. UserInputExceptionInvalidFilePath.
2. UserInputExceptionLoginCredential.
3. UserInputExceptionTestConfig.
4. UserInputExceptionYAMLFormat
5. UserAppException
**Validation**
- Unittesting
- Manual Testing
**Console Output Scenarios** 
- <img width="800" alt="image" src="https://github.com/microsoft/PowerApps-TestEngine/assets/98551644/4e126fab-8a8a-43e6-a54c-a79f68bac0a9">
- <img width="800" alt="image" …
> Adding UserInput or UserApp Exceptions

- docs/Yaml/testSettings.md
enablePowerFxOverlay is a setting that we're not implementing in Test Engine. It appears that it was intended to be implemented at some point, but never was. Removing it from the doc for now.
> Remove enablePowerFxOverlay from Test Settings doc

- src/Microsoft.PowerApps.TestEngine.Tests/Config/TestStateTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/Config/YamlTestConfigParserTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/ConsoleOutputTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/TestEngineTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/Users/UserManagerTests.cs
- src/Microsoft.PowerApps.TestEngine/Config/TestState.cs
- src/Microsoft.PowerApps.TestEngine/Config/YamlTestConfigParser.cs
- src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
- src/Microsoft.PowerApps.TestEngine/System/UserInputException.cs
- src/Microsoft.PowerApps.TestEngine/TestEngine.cs
- src/Microsoft.PowerApps.TestEngine/TestEngineEventHandler.cs
- src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs
- src/Microsoft.PowerApps.TestEngine/Users/UserManager.cs
Handling invalid user test settings values like locale and browser
**Currently** the exception thrown is not handled properly. This causes consuming application to encounter error.
**Proposing** handling this scenario like any other **user input exception and gracefully**.
> Handling invalid user input testsettings

- src/Microsoft.PowerApps.TestEngine.Tests/ConsoleOutputTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/TestEngineTests.cs
- src/Microsoft.PowerApps.TestEngine/System/UserInputException.cs
- src/Microsoft.PowerApps.TestEngine/TestEngine.cs
- src/Microsoft.PowerApps.TestEngine/TestEngineEventHandler.cs
- src/PowerAppsTestEngine/Program.cs
If output directory exists but is invalid, such as a drive doesn't exist, handle this properly so this doesn't throw an unknown error up the chain.
> Handle Invalid Output Directory

- src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppFunctionsTest.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/Functions/SetPropertyFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/Functions/SomeOtherUntypedObject.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/Functions/WaitFunctionTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/PowerFxEngineTests.cs
- src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
PowerFx version update.
Please note that `currently PowerApps does not support decimal fully but floating-point numbers` which was handled here https://github.com/microsoft/PowerApps-TestEngine/pull/278. 
Whereas, PowerFx by default considers numbers as decimal. Hence in the tests we had to convert number to right type since we do not handle case for decimal types yet in testengine.
Tested the new version with PAC CLI. Looks good and runs well.
> Update PowerFx to 1.1

- .github/workflows/build-test.yml
- src/testengine.provider.mda.tests/ModelDrivenApplicationProviderTest.cs
- src/testengine.provider.mda/ModelDrivenApplicationProvider.cs
- src/testengine.user.certificate.tests/CertificateUserManagerModuleTests.cs
- src/testengine.user.certificate/CertificateUserManagerModule.cs
> embedding script and cert failed validation

- src/Microsoft.PowerApps.TestEngine.Tests/Modules/TestEngineExtensionCheckerTests.cs
- src/Microsoft.PowerApps.TestEngine.Tests/Modules/TestEngineModuleMEFLoaderTests.cs
- src/Microsoft.PowerApps.TestEngine/Config/TestSettingExtensionSource.cs
- src/Microsoft.PowerApps.TestEngine/Config/TestSettingExtensions.cs
- src/Microsoft.PowerApps.TestEngine/Modules/TestEngineExtensionChecker.cs
- src/Microsoft.PowerApps.TestEngine/Modules/TestEngineModuleMEFLoader.cs
- src/Microsoft.PowerApps.TestEngine/System/FileSystem.cs
- src/Microsoft.PowerApps.TestEngine/Users/IUserManager.cs
- src/PowerAppsTestEngine/Program.cs
- src/testengine.provider.mda/ModelDrivenApplicationProvider.cs
- src/testengine.user.storagestate.tests/StorageStateUserManagerModuleTests.cs
- src/testengine.user.storagestate/StorageStateUserManagerModule.cs
Restricts usage of settings and extensions conditionally to a specific set
- [-] The code change is covered by unit tests. I have added tests that prove my fix is effective or that my feature works
- [-] I have performed end-to-end test locally.
- [-] New and existing unit tests pass locally with my changes
- [-] I have commented my code, particularly in hard-to-understand areas
- [-] My changes generate no new warnings
- [-] I used clear names for everything
- [-] I have performed a self-review of my own code
> restrict to specific list of providers and allow settings

- .azurepipelines/azure-pipelines-1ES.yml
- samples/template/TestPlanTemplate.fx.yaml
> Integration
