microsoft/PowerApps-TestEngine

src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs

Add more logs during the setup process to help debug.

Add more logs during setup

---

README.md
samples/basicgallery/testPlanForRegionUsePeriodAsDecimalSeparator.fx.yaml

Add notes in Readme and a sample test plan for languages and regions that use period as the decimal separator

Localization fix

---

docs/CommandInput.md

Remove final readme doc about conversion code, that's been removed.

Remove extra conversion readme

---

.github/workflows/build-test.yml

Add notification for GitHub action schedule run.
Notification will be look like below when schedule failed.

Github action scheduled notification

---

src/Microsoft.PowerApps.TestEngine.Tests/Helpers/ExceptionHandlingHelperTest.cs
src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppFunctionsTest.cs
src/Microsoft.PowerApps.TestEngine/Helpers/ExceptionHandlingHelper.cs
src/Microsoft.PowerApps.TestEngine/Helpers/PollingHelper.cs
src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs

- Merged JSSDK feature branch changes
- Resolve conflicts and make sure it works for both legacy and OnePlayer
- Did end to end testing with legacy player
- Did end to end testing regarding the case that users don't have an up-to-date published app

Merge JSSDK feature branch changes

---

build-pipelines/scripts/yaml-integration-tests.sh
src/Microsoft.PowerApps.TestEngine.Tests/PowerApps/PowerAppFunctionsTest.cs
src/Microsoft.PowerApps.TestEngine/Helpers/PollingHelper.cs
src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs

Should not print error when polling for old player.

Create and use new PollAsync that does not throw an error

---

src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/Functions/SelectFunctionTests.cs
src/Microsoft.PowerApps.TestEngine/PowerFx/Functions/Select/SelectOneParamFunction.cs
src/Microsoft.PowerApps.TestEngine/PowerFx/Functions/Select/SelectThreeParamsFunction.cs
src/Microsoft.PowerApps.TestEngine/PowerFx/Functions/Select/SelectTwoParamsFunction.cs

Add Logging for Select Function

Add Logging for Select Function

---

samples/buttonclicker/testPlan.fx.yaml
samples/calculator/testPlanWithCommaForDecimal.fx.yaml
samples/differentvariabletypes/testPlan.fx.yaml
samples/differentvariabletypes/testPlanAppIdPreprod.fx.yaml
samples/differentvariabletypes/testPlanAppIdPreview.fx.yaml
samples/differentvariabletypes/testPlanAppIdTest.fx.yaml
samples/testSettings.yaml

Added the `locale` property to the testSettings.yaml sample file as well. This is not a breaking change, and was missed in a previous PR.
- [N/A] The code change is covered by unit tests. I have added tests that prove my fix is effective or that my feature works
- [N/A] I have performed end-to-end test locally.
- [N/A] New and existing unit tests pass locally with my changes
- [N/A] I have commented my code, particularly in hard-to-understand areas

added locale to testSettings.yaml sample file

---

src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
src/nuget.config

This is discovered when onboarding to Component Governance.

Remove unused config.

---

src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
src/Microsoft.PowerApps.TestEngine/Reporting/ITestLogger.cs
src/Microsoft.PowerApps.TestEngine/Reporting/TestLogger.cs
src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs

Remove stack-trace from console and put it in the case or suite it executed from.

Remove Stack-Traces from Console Output

---

azure-pipelines.yml
src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj

Using MinVer for Package Versioning. 
How it works -> https://github.com/adamralph/minver#how-it-works
https://github.com/adamralph/minver#can-i-bump-the-major-or-minor-version

Using MinVer for Package Versioning 

---

src/Microsoft.PowerApps.TestEngine/Reporting/TestLogger.cs
src/Microsoft.PowerApps.TestEngine/TestEngine.cs

Added an exception handler for `outputDirectory`, reorganized input argument handlers inside `RunTestAsync`, removed some duplicate log messages and improved a few other messages.

Improved Exception handling and messages for some input arguments

---

docs/Yaml/testSettings.md
src/Microsoft.PowerApps.TestEngine.Tests/TestEngineTests.cs
src/Microsoft.PowerApps.TestEngine/Config/ITestState.cs
src/Microsoft.PowerApps.TestEngine/Config/TestSettings.cs
src/Microsoft.PowerApps.TestEngine/Config/TestState.cs
src/Microsoft.PowerApps.TestEngine/TestEngine.cs

Currently with multiple browser config
Running sequentially and keeping the logs clean.

Handle multiple browsers sequentially

---

src/Microsoft.PowerApps.TestEngine.Tests/Helpers/LoggingHelpersTest.cs
src/Microsoft.PowerApps.TestEngine/Helpers/LoggingHelper.cs

Debug Info should be Information level not trace

Debug | Trace to Info

---

src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
targets/Program.cs
targets/targets.csproj

Versioning

---

src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs

Bug-fix + improvements thanks to @Grant-Archibald-MS 
- Fixed Race Condition
- Fixed Login Issues
- Upgraded to Playwright 1.33.0

Fix Race Condition, Login Issues + Upgrade Playwright ver

---

src/Microsoft.PowerApps.TestEngine/System/AssertionFailureException.cs

AssertionFailureException only had one use. Adding all three overload possibilities for future use.

AssertionFailureException Update

---

src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs

Reverts microsoft/PowerApps-TestEngine#253

Revert "Fix Race Condition, Login Issues + Upgrade Playwright ver"

---

src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs

Attempt to improve stability of testengine by updating the Playwright version used 1.35.0. 
Also includes the improvements from https://github.com/microsoft/PowerApps-TestEngine/pull/253  (Fix Race Condition, Login Issues + Upgrade Playwright ver )
Thanks to @Grant-Archibald-MS for the above contribution.
Error below happens currently when memory overload or CPU utilization is high and we run TestEngine.

PW Upgrade and improving login

---

src/Microsoft.PowerApps.TestEngine.Tests/PowerFx/PowerFxHelperTests.cs
src/Microsoft.PowerApps.TestEngine/PowerApps/PowerAppFunctions.cs
src/Microsoft.PowerApps.TestEngine/PowerFx/Functions/WaitFunction.cs

Removing TODOs

---

.github/workflows/build-test.yml

This PR temporarily disables the yaml integration tests job specifically for the TEST environment - this is to mitigate an ongoing infrastructure issue and unblock currently open PRs.
- [N/A] The code change is covered by unit tests. I have added tests that prove my fix is effective or that my feature works
- [N/A] I have performed end-to-end test locally.
- [N/A] New and existing unit tests pass locally with my changes
- [N/A] I have commented my code, particularly in hard-to-understand areas
- [N/A] I have made corresponding changes to the documentation
- [N/A] My changes generate no new warnings

Temporarily disable test env integration test job

---

README.md

Updates the Test Engine documentation for "known limitations" to point to the official docs.

Update known limitations docs

---

README.md

Updating playwright installation step

Updating playwright installation step

---

src/Microsoft.PowerApps.TestEngine.Tests/Microsoft.PowerApps.TestEngine.Tests.csproj
src/PowerAppsTestEngine/PowerAppsTestEngine.csproj

NuGet Package update System.Text.Json

---

samples/coe-kit-setup-wizard/README.md
samples/permissions/README.md
src/Microsoft.PowerApps.TestEngine.Tests/Helpers/PollingHelpersTest.cs

Minor updates to the documentation to correct the branch name in the samples

Post merge update

---

samples/README.md
src/PowerAppsTestEngine/Program.cs

Minor update on #489 to clarify wait and debug instructions on how to attach to Power Apps Test Engine using Visual Studio Code.

Update to wait and debug instructions

---

.azurepipelines/azure-pipelines-1ES.yml
.github/workflows/build-test.yml

adding securityevents write for codeql and publishing debug art

---

src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/TestRecorderTests.cs
src/Microsoft.PowerApps.TestEngine/TestInfra/TestRecorder.cs
src/PowerAppsTestEngine.sln
src/testengine.provider.mda/PowerAppsTestEngineMDACustom.js

Enhanced Record and Replay

---

src/testengine.user.storagestate/DataverseStorageStateUserManagerModule.cs

Update DataverseStorageStateUserManagerModule.cs machine name

---

src/Microsoft.PowerApps.TestEngine.Tests/Config/YamlTestConfigParserTests.cs
src/Microsoft.PowerApps.TestEngine.Tests/Modules/TestEngineExtensionCheckerTests.cs
src/Microsoft.PowerApps.TestEngine.Tests/SingleTestRunnerTests.cs
src/Microsoft.PowerApps.TestEngine.Tests/System/FileSystemTests.cs
src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
src/Microsoft.PowerApps.TestEngine/Config/TestSettings.cs
src/Microsoft.PowerApps.TestEngine/SingleTestRunner.cs
src/Microsoft.PowerApps.TestEngine/System/FileSystem.cs
src/Microsoft.PowerApps.TestEngine/System/IFileSystem.cs
src/Microsoft.PowerApps.TestEngine/TestInfra/ITestInfraFunctions.cs
src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs
src/Microsoft.PowerApps.TestEngine/Users/IUserManager.cs
src/PowerAppsTestEngineWrapper/InputOptions.cs
src/PowerAppsTestEngineWrapper/Program.cs
src/testengine.common.user/LoginState.cs
src/testengine.common.user/PowerPlatformLogin.cs
src/testengine.provider.powerapps.portal.tests/PowerAppPortalProviderTest.cs
src/testengine.provider.powerapps.portal/PowerAppPortalProvider.cs
src/testengine.user.storagestate/StorageStateUserManagerModule.cs

- [-] The code change is covered by unit tests. I have added tests that prove my fix is effective or that my feature works
- [-] I have performed end-to-end test locally.
- [-] New and existing unit tests pass locally with my changes
- [-] I have commented my code, particularly in hard-to-understand areas
- [-] My changes generate no new warnings
- [-] I used clear names for everything
- [-] I have performed a self-review of my own code

use static context with storagestate

---

samples/template/TestPlanTemplate.fx.yaml

Update template TestPlanTemplate.fx.yaml

---

src/Microsoft.PowerApps.TestEngine/TestInfra/MicrosoftEntraNetworkMonitor.cs
src/testengine.module.simulation/SimulateDataverseFunction.cs

change schema

---

samples/basicgallery/testPlan.fx.yaml
samples/calculator/testPlanWithCommaForDecimal.fx.yaml
samples/connector/testPlan.fx.yaml
src/Microsoft.PowerApps.TestEngine.Tests/Provider/PowerFXModel/ControlRecordValueTests.cs
src/Microsoft.PowerApps.TestEngine.Tests/Provider/PowerFXModel/ControlTableValueTests.cs
src/Microsoft.PowerApps.TestEngine/Providers/PowerFxModel/ControlTableValue.cs
src/PowerAppsTestEngineWrapper/Program.cs

Updated message and samples. Updating Controltablevalue per provider type to maintain backward compatibility
- [-] The code change is covered by unit tests. I have added tests that prove my fix is effective or that my feature works
- [-] I have performed end-to-end test locally.
- [-] New and existing unit tests pass locally with my changes
- [-] I have commented my code, particularly in hard-to-understand areas
- [-] I have made corresponding changes to the documentation
- [-] My changes generate no new warnings
- [-] I used clear names for everything
- [-] I have performed a self-review of my own code

Update log message and sample cases, table value row name

---

src/Microsoft.PowerApps.TestEngine.Tests/Config/YamlTestConfigParserTests.cs
src/Microsoft.PowerApps.TestEngine.Tests/System/FileSystemTests.cs
src/Microsoft.PowerApps.TestEngine/Config/YamlTestConfigParser.cs
src/Microsoft.PowerApps.TestEngine/PowerFx/Functions/ScreenshotFunction.cs
src/Microsoft.PowerApps.TestEngine/System/FileSystem.cs
src/Microsoft.PowerApps.TestEngine/TestEngineEventHandler.cs
src/testengine.module.playwrightaction/PlaywrightActionValueFunction.cs

Message updates and path separator validation.
- [-] The code change is covered by unit tests. I have added tests that prove my fix is effective or that my feature works
- [-] I have performed end-to-end test locally.
- [-] New and existing unit tests pass locally with my changes
- [-] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [-] My changes generate no new warnings
- [-] I used clear names for everything
- [-] I have performed a self-review of my own code

msg update and adding separator for directory access

---

samples/copilotstudiokit/RunTests.ps1
samples/dataverse/RunTests.ps1
samples/mdainputcontrols/README.md

Using alias for provider parameter.

setting provider to avoid confusion, warnings

---

samples/copilotstudiokit/RunTests.ps1

Using alias for provider parameter.

setting provider to avoid avoid warning

---

src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/PlaywrightTestInfraFunctionTests.cs
src/Microsoft.PowerApps.TestEngine/TestInfra/PlaywrightTestInfraFunctions.cs

Adding headless mode for chromium as part of the args.

adding new headless mode for chromium

---

src/Microsoft.PowerApps.TestEngine/Modules/TestEngineModuleMEFLoader.cs
src/PowerAppsTestEngine/PowerAppsTestEngine.csproj
src/PowerAppsTestEngineWrapper/PowerAppsTestEngineWrapper.csproj

powerfx provider, temporary visualcompare removal

---

src/Microsoft.PowerApps.TestEngine.Tests/TestInfra/MicrosoftEntraNetworkMonitorTests.cs
src/Microsoft.PowerApps.TestEngine/Microsoft.PowerApps.TestEngine.csproj
src/PowerAppsTestEngineWrapper/PowerAppsTestEngineWrapper.csproj
src/testengine.common.user/testengine.common.user.csproj
src/testengine.module.mda/testengine.module.mda.csproj
src/testengine.module.pause/testengine.module.pause.csproj
src/testengine.module.powerapps.portal/testengine.module.powerapps.portal.csproj
src/testengine.module.simulation/testengine.module.simulation.csproj

Update from 1.48.0 to 1.52.0 for Microsoft Playwright in the solution

Update to Playwright 1.52.0
